### ISSUE TITLE
Working settings

### ISSUE THREAD

**Issue by tja4472** [firebase/emulators-codelab#2]
These settings worked for me.

firebase-tools@7.10.0

## functions\package.json

```json
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "test": "mocha --timeout 10000",
    "test_all": "mocha test_all.js --timeout 10000"
  },
  "engines": {
    "node": "8"
  },
  "dependencies": {
    "file-system": "2.2.2",
    "firebase-admin": "8.8.0",
    "firebase-functions": "3.3.0"
  },
  "devDependencies": {
    "@firebase/testing": "0.16.3",
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1",
    "firebase-functions-test": "0.1.7",
    "mocha": "6.2.2"
  },
  "private": true
}
```

## public\index.html

```html
<script src="/__/firebase/7.6.0/firebase-app.js"></script>
<script src="/__/firebase/7.6.0/firebase-auth.js"></script>
<script src="/__/firebase/7.6.0/firebase-firestore.js"></script>
<script src="/__/firebase/init.js"></script>
```

### 1. Getting started with the Firebase Local Emulator Suite

https://google.dev/codelabs/firebase-emulator-get-started?playlist-id=firebase-emulators#0

### 2. Test-drive Firestore Security Rules

https://google.dev/codelabs/firebase-emulator-test-rules#0

### 3. Test-drive Complex Firebase Functions

https://google.dev/codelabs/firebase-emulators-test-functions#0

**Comment by samtstern** [comment]
@tja4472 is there an issue with the codelab or something you want to see changed?

**Comment by tja4472** [comment]
@samtstern 

Using firebase-tools@7.10.0 and with no changes to the codelab, I get:

## firebase emulators:start

```sh
Microsoft Windows [Version 10.0.18363.535]
(c) 2019 Microsoft Corporation. All rights reserved.

c:\VSCode\2019\temp\codelab-issue\emulators-codelab\codelab-final-state>firebase emulators:start
i  emulators: Starting emulators: functions, firestore, hosting
!  Your requested "node" version "8" doesn't match your global version "10"
+  functions: Emulator started at http://localhost:5001
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
!  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
i  firestore: Emulator logging to firestore-debug.log
+  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  hosting: Serving hosting files from: public
+  hosting: Local server: http://localhost:5000
+  hosting: Emulator started at http://localhost:5000
i  functions: Watching "c:\VSCode\2019\temp\codelab-issue\emulators-codelab\codelab-final-state\functions" for Cloud Functions...
!  TypeError: instance.INTERNAL.registerComponent is not a function
    at registerDatabase (c:\VSCode\2019\temp\codelab-issue\emulators-codelab\codelab-final-state\functions\node_modules\@firebase\database\dist\index.node.cjs.js:15168:39)     
    at Object.<anonymous> (c:\VSCode\2019\temp\codelab-issue\emulators-codelab\codelab-final-state\functions\node_modules\@firebase\database\dist\index.node.cjs.js:15200:5)    
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at FirebaseNamespace.get [as database] (c:\VSCode\2019\temp\codelab-issue\emulators-codelab\codelab-final-state\functions\node_modules\firebase-admin\lib\firebase-namespace.js:282:38)
!  We were unable to load your functions code. (see above)
```
## functions>npm test

```sh
c:\VSCode\2019\temp\codelab-issue\emulators-codelab\codelab-final-state\functions>npm test

> functions@ test c:\VSCode\2019\temp\codelab-issue\emulators-codelab\codelab-final-state\functions
> mocha



  1) "before all" hook in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.




npm ERR! Test failed.  See above for more details.
```

**Comment by samtstern** [comment]
@tja4472 thanks for explaining!  Going to move this issue over to the FIrebase JS SDK repository for investigation.
